root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/aagent ./cmd/aagent"
bin = "./tmp/aagent"
full_bin = "./tmp/aagent server --port 8080"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "web-app", "mind", ".git", ".gocache"]
exclude_regex = ["_test.go"]
delay = 1000
stop_on_error = false
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[misc]
clean_on_exit = true
